#### 1. Write a function so that the columns of the output matrix are powers of the input vector.


In [40]:
import numpy as np
def np_vander(ip_vector, N, increasing = False):
    if not increasing:
         op_vector = np.column_stack([ip_vector_1**(N-1-i) for i in range(N)])
    elif increasing:
        op_vector = np.array([x**i for x in ip_vector for i in range(N)]).reshape(ip_vector.size,N)
    
    return op_vector

ip_vector_1 = np.array([1,2,3,5,6])
N_columns = 3
out_vector_dec = np_vander(ip_vector_1, N_columns, False)
out_vector_inc = np_vander(ip_vector_1, N_columns, True)
print ("The deceasing order\n",out_vector_dec)
print ("The Increasing Order\n",out_vector_inc)


The deceasing order
 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [25  5  1]
 [36  6  1]]
The Increasing Order
 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  5 25]
 [ 1  6 36]]


#### 2. Write a function to find moving average in an array over a window:
- Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.
- ''' Problem Statement 2:
- Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
- the given sequence is defined as follows:
- The moving average sequence has n-k+1 elements as shown below.
- The moving averages with k=4 of a ten-value sequence (n=10) is shown below
- i 1 2 3 4 5 6 7 8 9 10
- ===== == == == == == == == == == ==
 - Input 10 20 30 40 50 60 70 80 90 100
-  y1 25 = (10+20+30+40)/4
-  y2 35 = (20+30+40+50)/4
-  y3 45 = (30+40+50+60)/4
-  y4 55 = (40+50+60+70)/4
-  y5 65 = (50+60+70+80)/4
-  y6 75 = (60+70+80+90)/4
-  y7 85 = (70+80+90+100)/4
- Thus, the moving average sequence has n-k+1=10-4+1=7 values.'''

In [6]:
import numpy as np

In [12]:
x = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]

def mov_avg(x, win):
    for m in range(len(x)-(win-1)):
        yield sum(np.ones(win) * x[m:m+win]) / win 

In [13]:
list(mov_avg(x,3))

[5.0,
 4.666666666666667,
 5.666666666666667,
 6.666666666666667,
 9.666666666666666,
 28.666666666666668,
 49.333333333333336,
 72.66666666666667,
 84.0,
 93.33333333333333,
 116.33333333333333]